<?php $_productCollection = $this->getLoadedProductCollection() ?>
<div class="block-image-slider">
    <div class="block-title">
        <h2><?php echo $this->getTitle() ?></h2>
    </div>
    <div class="productslider-container">
        <div id="productslider-<?php echo $this->getCategoryId() ?>">
            <?php foreach ($_productCollection as $_product): ?>
            <div class="slider-item">
              <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="carousel-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250); ?>" width="250" height="250" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
              <div class="slider-item-content">
                <p>
                  <?php echo $_product->getName() ?>
                </p>
                <?php echo $this->getPriceHtml($_product) ?>
              </div>
            </div>
            <?php endforeach; ?>
        </div>
        <div class="productslider-controls">
            <a id="btn-prev-<?php echo $this->getCategoryId() ?>" class="btn-prev" href="#">&lt;</a>
            <a id="btn-next-<?php echo $this->getCategoryId() ?>" class="btn-next" href="#">&gt;</a>
            <div id="pager-<?php echo $this->getCategoryId() ?>" class="pager"></div>
        </div>
    </div>
</div>
<script type="text/javascript">

jQuery(document).ready(function(){
    jQuery("#productslider-<?php echo $this->getCategoryId() ?>").carouFredSel({
        width: '100%',
        prev: '#btn-prev-<?php echo $this->getCategoryId() ?>',
        next: '#btn-next-<?php echo $this->getCategoryId() ?>',
        pagination: '#pager-<?php echo $this->getCategoryId() ?>'
    });
});
 
</script>